<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_product = $block->getProduct() ?>
<?php if ($block->canEmailToFriend()): ?>
    <a href="<?= /* @escapeNotVerified */ $this->helper('Magento\Catalog\Helper\Product')->getEmailToFriendUrl($_product) ?>"
       class="action mailto friend feature feature-icon-hover" title="<?= /* @escapeNotVerified */ __('Email') ?>">
       <span class="icon ib ib-hover ic ic-letter icon-color-productview"></span>  
       <span class="label"><?= /* @escapeNotVerified */ __('Email') ?></span></a>
<?php endif; ?>
