<?php
    $theme = $this->helper('Infortis\Base\Helper\Data');
    $accountLinksHtml = '';
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $customerSession = $objectManager->create('Magento\Customer\Model\Session');

    //Default Magento Top Links
    if ($theme->getCfg('header/top_links'))
    {
        $accountLinksHtml .= $block->getChildHtml('top.links');
    }

    //Additional custom links
    if ($tmpHtml = $block->getChildHtml('block_header_top_links'))
    {
        $accountLinksHtml .= $tmpHtml;
    }
?>
<?php if ($accountLinksHtml): ?>
    <div id="header-account" class="account-links top-links links-wrapper-separators-left skip-content skip-content--style">
    <?php if ($customerSession->isLoggedIn()): ?>
            <div class="item local-font">
                <?php $customerName = $customerSession->getCustomer()->getName();  // get  Full Name ?>
                    <div class="welcome"><?php echo 'Welcome, '.$customerName.'!'; ?></div>
            </div>
        <?php else: ?>
                <?php if ($tmpHtml = $this->getWelcome()): ?>
                    <div class="item local-font">
                        <div class="welcome"><?php echo $tmpHtml; ?></div>
                    </div>
                <?php endif; ?>
        <?php endif; ?> 
        <?php echo $accountLinksHtml; ?>
    </div>
<?php endif; ?>
