<?php
// @codingStandardsIgnoreFile
?>
<div class="item link compare" data-bind="scope: 'compareProducts'" data-role="compare-products-link" title="Compare Products">
    <?php /* @escapeNotVerified */ echo __('<span class="icon ic ic-compare"></span>') ?> 
    <a class="action compare no-display" title="<?php /* @escapeNotVerified */ echo __('Compare Products'); ?>" data-bind="attr: {'href': compareProducts().listUrl}, css: {'no-display': !compareProducts().count}" target="_blank">
        <span class="counter qty" data-bind="text: compareProducts().countCaption"></span>
    </a>
</div>
<script type="text/x-magento-init">
    {"[data-role=compare-products-link]": {"Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>}}
</script>