<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $mediaUrl =$storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
    $_storeCode = $storeManager->getStore()->getCode();

   //boolean variable was made for storebuild automation to eneble/disable blocks
    $isAppointmentForm = true;
    $formId = '1';

    if($isAppointmentForm): ?>

        <section class="appt-request container" id="request_appointment">
            <div class="img-container desktop" style="background: url('<?php echo $mediaUrl?>wysiwyg/<?php echo $_storeCode?>/request-appointment.jpg') no-repeat;">
            </div>
            <div class="img-container mobile" style="background: url('<?php echo $mediaUrl?>wysiwyg/<?php echo $_storeCode?>/request-appointment-mobile.jpg') no-repeat;">
            </div>
            <div class="form-container">
                <h2>REQUEST AN APPOINTMENT</h2>
                <p class="small">*required fields</p>
                <?= $this->getLayout()
                         ->createBlock("VladimirPopov\WebForms\Block\Widget\Form")
                         ->setWebformId($formId)
                         ->setAfterSubmissionForm("0")
                         ->setScrollTop("0")
                         ->setTemplate("webforms/form/default.phtml")
                         ->toHtml();
                ?>
            </div>
        </section>
    <?php endif; ?>
