<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $mediaUrl =$storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

    $storeInformation = $objectManager->create('Magento\Store\Model\Information');
    $store = $objectManager->create('Magento\Store\Model\Store');
    $storeInfo = $storeInformation->getStoreInformationObject($store);
    $storeName = $storeInfo->getData("name");
    $_storeCode = $storeManager->getStore()->getCode();
?>

<div class="grid12-12 footer-block1">
    <a href=" <?php echo $block->getBaseUrl(); ?>" title="<?php echo $storeName ?>" >
        <img src="<?php echo $mediaUrl ?>wysiwyg/<?php echo $_storeCode ?>/footer-logo.png" alt="" />
    </a>
</div>
<div style="clear:both;"></div>