<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $mediaUrl =$storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
    $_storeCode = $storeManager->getStore()->getCode();

    //boolean variable was made for storebuild automation to eneble/disable blocks
    $isReward = true;

    $content = 'Shop online at our store for your favorite skincare products, cosmetic procedures and treatment packages. <br/> Register for a free account on the store and earn 5% back in reward points on every purchase!';

   if ($isReward) :?>
        <div class="mask-container">
            <section class="products-section container" >
            <img src="<?php echo $mediaUrl?>wysiwyg/<?php echo $_storeCode?>/rewards.png" alt="" />
            <div class="prod-desc">
                    <h2>rewards program</h2>
                    <h3>Earn Rewards Every Time You Shop Online</h3>
                    <p><?= $content ?></p>
                    <a href=" <?php echo $block->getBaseUrl(); ?>rewardpointsinfo"  title="Learn More" class="action primary">Learn More</a>
            </div>

            </section>
            <div class="bg-mask"></div>
        </div>
    <?php endif; ?>
