<?php
  $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
  $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
  $mediaUrl =$storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
  $_storeCode = $storeManager->getStore()->getCode();

  $baseUrl = $block->getBaseUrl();

  //boolean variable was made for storebuild automation to eneble/disable blocks
  $isCta = true;

  $verticalCtaName = "Body";
  $horizontalTopCtaName = "Face";
  $horizontalBottomCtaName = "Skin";

  $verticalCtaId = ['2032', '898', '2619', '899', '911', '914'];
  $horizontalTopCtaId = ['2032', '898', '2619', '899'];
  $horizontalBottomCtaId = ['2619', '899', '911', '914'];

  $verticalCtaViewId = '154';
  $horizontalTopCtaViewId = '154';
  $horizontalBottomCtaViewId = '154';

  if ($isCta) { ?>
  <section class="cta-section container">
    <div class="flex-row">
      <div class="vert-container">
        <div class="cta-box">
            <img class="cta-image" src="https://labaesthetics.shop/media/wysiwyg/labaesthetics/BODY.jpg" alt="">
            <img class="cta-image-mobile" src="https://labaesthetics.shop/media/wysiwyg/labaesthetics/GettyImages-855101598_1.png" alt="" width="100%">
            <!-- <img class="cta-image" src="<?php echo $mediaUrl?>wysiwyg/<?php echo $_storeCode?>/CTA-Body.jpg" alt="">
            <img class="cta-image-mobile" src="<?php echo $mediaUrl?>wysiwyg/<?php echo $_storeCode?>/CTA-mobile-Body.jpg" alt="" width="100%"> -->
            <div class="cta-name"><?= $verticalCtaName; ?></div>
            <div class="cta-mask flex-column">
                <div class="cat-name"><?= $verticalCtaName; ?></div>
                <div class="links-list flex-column flex-y-center">
                  <?php foreach ($verticalCtaId as $catId) {
      $category = $objectManager->create('Magento\Catalog\Model\Category')->load($catId);
      $categoryName = $category->getName();
      $categoryUrlPath = $category->getUrlPath();
      $baseUrl = $block->getBaseUrl(); ?>
                    <a class="cat-link" href="<?= $baseUrl . $categoryUrlPath; ?>"><?= $categoryName; ?></a>
                  <?php
  } ?>
                </div>
                <?php
                    $verticalCategory = $objectManager->create('Magento\Catalog\Model\Category')->load($verticalCtaViewId);
                    $verticalCategoryUrlPath = $verticalCategory->getUrlPath();
                ?>
                <a class="cat-btn action primary" href="<?= $baseUrl . $verticalCategoryUrlPath; ?>" title="View All">View All</a>
            </div>
        </div>
      </div>
      <div class="horiz-contaier flex-column">
      <div class="cta-box">
            <img src="https://labaesthetics.shop/media/wysiwyg/labaesthetics/FACE.jpg" alt="">
            <img class="cta-image-mobile" src="https://labaesthetics.shop/media/wysiwyg/labaesthetics/GettyImages-1085632092_1.png" alt="" width="100%">
            <!-- <img src="<?php echo $mediaUrl?>wysiwyg/<?php echo $_storeCode?>/CTA-Face.jpg" alt="">
            <img class="cta-image-mobile" src="<?php echo $mediaUrl?>wysiwyg/<?php echo $_storeCode?>/CTA-mobile-Face.jpg" alt="" width="100%"> -->
            <div class="cta-name"><?= $horizontalTopCtaName; ?></div>
            <div class="cta-mask flex-column">
                <div class="cat-name">Popular <?= $horizontalTopCtaName; ?> Procedures</div>
                <div class="links-list flex-row flex-y-center flex-wrap">
                <?php foreach ($horizontalTopCtaId as $catId) {
                    $category = $objectManager->create('Magento\Catalog\Model\Category')->load($catId);
                    $categoryName = $category->getName();
                    $categoryUrlPath = $category->getUrlPath(); ?>
                    <a class="cat-link flex-grid-2" href="<?= $baseUrl . $categoryUrlPath; ?>"><?= $categoryName; ?></a>
                  <?php
                } ?>
                </div>
                <?php
                    $horizontalTopCategory = $objectManager->create('Magento\Catalog\Model\Category')->load($horizontalTopCtaViewId);
                    $horizontalTopCategoryUrlPath = $horizontalTopCategory->getUrlPath();
                ?>
                <a class="cat-btn action primary" href="<?= $baseUrl . $horizontalTopCategoryUrlPath ?>" title="View All">View All</a>
            </div>
        </div>
          <div class="cta-box">
          <img src="https://labaesthetics.shop/media/wysiwyg/labaesthetics/SKIN.jpg" alt="">
          <img class="cta-image-mobile" src="https://labaesthetics.shop/media/wysiwyg/labaesthetics/GettyImages-910856488_1.png" alt="" width="100%">
          <!-- <img src="<?php echo $mediaUrl?>wysiwyg/<?php echo $_storeCode?>/CTA-Skin.jpg" alt="">
          <img class="cta-image-mobile" src="<?php echo $mediaUrl?>wysiwyg/<?php echo $_storeCode?>/CTA-mobile-Skin.jpg" alt="" width="100%"> -->
            <div class="cta-name"><?= $horizontalBottomCtaName ?></div>
            <div class="cta-mask flex-column">
                <div class="cat-name">Popular <?= $horizontalBottomCtaName ?> Procedures</div>
                <div class="links-list flex-row flex-y-center flex-wrap">
                <?php foreach ($horizontalBottomCtaId as $catId) {
                    $category = $objectManager->create('Magento\Catalog\Model\Category')->load($catId);
                    $categoryName = $category->getName();
                    $categoryUrlPath = $category->getUrlPath(); ?>
                    <a class="cat-link flex-grid-2" href="<?= $baseUrl . $categoryUrlPath; ?>"><?= $categoryName; ?></a>
                  <?php
                } ?>
                </div>
                <?php
                    $horizontalBottomCategory = $objectManager->create('Magento\Catalog\Model\Category')->load($horizontalBottomCtaViewId);
                    $horizontalBottomCategoryUrlPath = $horizontalBottomCategory->getUrlPath();
                ?>
                <a class="cat-btn action primary" href="<?= $baseUrl . $horizontalBottomCategoryUrlPath ?>" title="View All">View All</a>
            </div>
        </div>
      </div>
    </div>
  </section>
<?php } ?>
