<div class="grid12-12 footer-block3" >
    <div class="flex-row">
        <img class="schedule-watch" src='<?php echo $this->getViewFileUrl('images/watch.svg'); ?>' alt="hours">
        <div class="flex-column">
            <p class="secondary">Monday - Friday <br/>10:00AM - 5:00PM</p>
            <p class="secondary">Saturday <br/>10:00AM - 4:00PM</p>
            <p class="secondary">Sunday - Closed</p>
        </div>
    </div>
    <div class="flex-row">
        <?php echo $this->getLayout()->createBlock("Hireindians\Storeautomation\Block\Socialicons")->setTemplate("Hireindians_Storeautomation::socialicons.phtml")->toHtml() ?>
    </div>
    <p class="no-padding">
        <a href="https://www.carecredit.com/apply/confirm.html?encm=AGEGP1IwVjMNMQBkWm9ZMQ48VTUDZ1NgAGVSagRuAjQ&sitecode=B3CALAdToolkitANCardCosmetic" title="CareCredit" target="_blank">
           <img src="<?php echo $this->getViewFileUrl('images/Care_Credit_Logo.png'); ?>" />
        </a>
    </p>

</div>
