<div class="footer-menu-bottom">
    <div class="security-links">
       <a href="http://www.positivessl.com/" target="_blank" title=""><img src="<?php echo $this->getViewFileUrl('images/comodo-secure-logo.png'); ?>" alt=""></a>
       <a title=""><img src="<?php echo $this->getViewFileUrl('images/Secured-By-CardConnect-logo.png'); ?>" alt=""></a>
    </div>
    <div class="menu-container">
       <a href="<?php echo $block->getBaseUrl(); ?>rewardpointsinfo" title="" class="menu-item">Rewards Program</a>
       <a href="<?php echo $block->getBaseUrl(); ?>fitzpatrick-scale" title="" class="menu-item">Fitzpatrick Scale</a>
       <a href="<?php echo $block->getBaseUrl(); ?>terms" title="" class="menu-item">Terms &amp; Conditions</a>
       <a href="<?php echo $block->getBaseUrl(); ?>return-policy" title="" class="menu-item">Return Policy</a>
    </div>
</div>